### ISSUE TITLE
Custom element doesn't exist via cloudfare tunnel

### ISSUE THREAD

**Issue by Deleny74** [CF209/van-tilt-sensor-custom-card#2]
Hi,

I integrated the custom card according to the instructions. When I open the dashboard directly on my homeassistant, everything works as expected. When I open the dashboard remotely via Cloudflare I get this message:
Custom element doesn't exist.

Do you have an solution for this problem?

![2024-04-01_19h12_29](https://github.com/CF209/van-tilt-sensor-custom-card/assets/155743991/c3a7ca9a-497a-44f2-a7d0-fed22da8f9d8)

**Comment by CzarofAK** [comment]
@Deleny74 did you solve it? i got the exact same thing, but on LAN...
